name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Maven
      uses: s4u/setup-maven-action@v1.2.1
      with:
        java-version: 17
    - name: Compile Minecraft Spigot (via BuildTools)
      uses: SpraxDev/Action-SpigotMC@v4.2.0
      with:
        versions: 1.19.4, 1.18.2, 1.17.1
        remapped: true
    - name: Build with Maven
      run: mvn package
